// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_pro.pro

package com.handwin.serializable.module;

public final class TextMessagePacketPro {
  private TextMessagePacketPro() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TextMessagePacketOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string cmsgID = 1;
    /**
     * <code>optional string cmsgID = 1;</code>
     */
    boolean hasCmsgID();
    /**
     * <code>optional string cmsgID = 1;</code>
     */
    java.lang.String getCmsgID();
    /**
     * <code>optional string cmsgID = 1;</code>
     */
    com.google.protobuf.ByteString
        getCmsgIDBytes();

    // optional bytes content = 2;
    /**
     * <code>optional bytes content = 2;</code>
     */
    boolean hasContent();
    /**
     * <code>optional bytes content = 2;</code>
     */
    com.google.protobuf.ByteString getContent();

    // optional string from = 3;
    /**
     * <code>optional string from = 3;</code>
     */
    boolean hasFrom();
    /**
     * <code>optional string from = 3;</code>
     */
    java.lang.String getFrom();
    /**
     * <code>optional string from = 3;</code>
     */
    com.google.protobuf.ByteString
        getFromBytes();

    // optional int32 messageId = 4;
    /**
     * <code>optional int32 messageId = 4;</code>
     */
    boolean hasMessageId();
    /**
     * <code>optional int32 messageId = 4;</code>
     */
    int getMessageId();

    // optional int32 messageServiceType = 5;
    /**
     * <code>optional int32 messageServiceType = 5;</code>
     */
    boolean hasMessageServiceType();
    /**
     * <code>optional int32 messageServiceType = 5;</code>
     */
    int getMessageServiceType();

    // optional int32 messageType = 6;
    /**
     * <code>optional int32 messageType = 6;</code>
     */
    boolean hasMessageType();
    /**
     * <code>optional int32 messageType = 6;</code>
     */
    int getMessageType();

    // optional int32 messageFlag = 7;
    /**
     * <code>optional int32 messageFlag = 7;</code>
     */
    boolean hasMessageFlag();
    /**
     * <code>optional int32 messageFlag = 7;</code>
     */
    int getMessageFlag();

    // optional int32 appID = 8;
    /**
     * <code>optional int32 appID = 8;</code>
     */
    boolean hasAppID();
    /**
     * <code>optional int32 appID = 8;</code>
     */
    int getAppID();

    // optional int32 vHead = 9;
    /**
     * <code>optional int32 vHead = 9;</code>
     */
    boolean hasVHead();
    /**
     * <code>optional int32 vHead = 9;</code>
     */
    int getVHead();

    // optional int32 packetSize = 10;
    /**
     * <code>optional int32 packetSize = 10;</code>
     */
    boolean hasPacketSize();
    /**
     * <code>optional int32 packetSize = 10;</code>
     */
    int getPacketSize();

    // optional int32 secrect = 11;
    /**
     * <code>optional int32 secrect = 11;</code>
     */
    boolean hasSecrect();
    /**
     * <code>optional int32 secrect = 11;</code>
     */
    int getSecrect();

    // optional int32 tempID = 12;
    /**
     * <code>optional int32 tempID = 12;</code>
     */
    boolean hasTempID();
    /**
     * <code>optional int32 tempID = 12;</code>
     */
    int getTempID();

    // optional int32 timeStamp = 13;
    /**
     * <code>optional int32 timeStamp = 13;</code>
     */
    boolean hasTimeStamp();
    /**
     * <code>optional int32 timeStamp = 13;</code>
     */
    int getTimeStamp();

    // optional int32 version = 14;
    /**
     * <code>optional int32 version = 14;</code>
     */
    boolean hasVersion();
    /**
     * <code>optional int32 version = 14;</code>
     */
    int getVersion();

    // optional bool zip = 15;
    /**
     * <code>optional bool zip = 15;</code>
     */
    boolean hasZip();
    /**
     * <code>optional bool zip = 15;</code>
     */
    boolean getZip();

    // optional string toUser = 16;
    /**
     * <code>optional string toUser = 16;</code>
     */
    boolean hasToUser();
    /**
     * <code>optional string toUser = 16;</code>
     */
    java.lang.String getToUser();
    /**
     * <code>optional string toUser = 16;</code>
     */
    com.google.protobuf.ByteString
        getToUserBytes();

    // optional string traceID = 17;
    /**
     * <code>optional string traceID = 17;</code>
     */
    boolean hasTraceID();
    /**
     * <code>optional string traceID = 17;</code>
     */
    java.lang.String getTraceID();
    /**
     * <code>optional string traceID = 17;</code>
     */
    com.google.protobuf.ByteString
        getTraceIDBytes();
  }
  /**
   * Protobuf type {@code TextMessagePacket}
   */
  public static final class TextMessagePacket extends
      com.google.protobuf.GeneratedMessage
      implements TextMessagePacketOrBuilder {
    // Use TextMessagePacket.newBuilder() to construct.
    private TextMessagePacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TextMessagePacket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TextMessagePacket defaultInstance;
    public static TextMessagePacket getDefaultInstance() {
      return defaultInstance;
    }

    public TextMessagePacket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TextMessagePacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              cmsgID_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              content_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              from_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              messageId_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              messageServiceType_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              messageType_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              messageFlag_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              appID_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              vHead_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              packetSize_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              secrect_ = input.readInt32();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              tempID_ = input.readInt32();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              timeStamp_ = input.readInt32();
              break;
            }
            case 112: {
              bitField0_ |= 0x00002000;
              version_ = input.readInt32();
              break;
            }
            case 120: {
              bitField0_ |= 0x00004000;
              zip_ = input.readBool();
              break;
            }
            case 130: {
              bitField0_ |= 0x00008000;
              toUser_ = input.readBytes();
              break;
            }
            case 138: {
              bitField0_ |= 0x00010000;
              traceID_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.handwin.serializable.module.TextMessagePacketPro.internal_static_TextMessagePacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.handwin.serializable.module.TextMessagePacketPro.internal_static_TextMessagePacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket.class, com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket.Builder.class);
    }

    public static com.google.protobuf.Parser<TextMessagePacket> PARSER =
        new com.google.protobuf.AbstractParser<TextMessagePacket>() {
      public TextMessagePacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TextMessagePacket(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TextMessagePacket> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string cmsgID = 1;
    public static final int CMSGID_FIELD_NUMBER = 1;
    private java.lang.Object cmsgID_;
    /**
     * <code>optional string cmsgID = 1;</code>
     */
    public boolean hasCmsgID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string cmsgID = 1;</code>
     */
    public java.lang.String getCmsgID() {
      java.lang.Object ref = cmsgID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cmsgID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cmsgID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCmsgIDBytes() {
      java.lang.Object ref = cmsgID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmsgID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional bytes content = 2;
    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>optional bytes content = 2;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes content = 2;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    // optional string from = 3;
    public static final int FROM_FIELD_NUMBER = 3;
    private java.lang.Object from_;
    /**
     * <code>optional string from = 3;</code>
     */
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string from = 3;</code>
     */
    public java.lang.String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          from_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string from = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 messageId = 4;
    public static final int MESSAGEID_FIELD_NUMBER = 4;
    private int messageId_;
    /**
     * <code>optional int32 messageId = 4;</code>
     */
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 messageId = 4;</code>
     */
    public int getMessageId() {
      return messageId_;
    }

    // optional int32 messageServiceType = 5;
    public static final int MESSAGESERVICETYPE_FIELD_NUMBER = 5;
    private int messageServiceType_;
    /**
     * <code>optional int32 messageServiceType = 5;</code>
     */
    public boolean hasMessageServiceType() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 messageServiceType = 5;</code>
     */
    public int getMessageServiceType() {
      return messageServiceType_;
    }

    // optional int32 messageType = 6;
    public static final int MESSAGETYPE_FIELD_NUMBER = 6;
    private int messageType_;
    /**
     * <code>optional int32 messageType = 6;</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 messageType = 6;</code>
     */
    public int getMessageType() {
      return messageType_;
    }

    // optional int32 messageFlag = 7;
    public static final int MESSAGEFLAG_FIELD_NUMBER = 7;
    private int messageFlag_;
    /**
     * <code>optional int32 messageFlag = 7;</code>
     */
    public boolean hasMessageFlag() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 messageFlag = 7;</code>
     */
    public int getMessageFlag() {
      return messageFlag_;
    }

    // optional int32 appID = 8;
    public static final int APPID_FIELD_NUMBER = 8;
    private int appID_;
    /**
     * <code>optional int32 appID = 8;</code>
     */
    public boolean hasAppID() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 appID = 8;</code>
     */
    public int getAppID() {
      return appID_;
    }

    // optional int32 vHead = 9;
    public static final int VHEAD_FIELD_NUMBER = 9;
    private int vHead_;
    /**
     * <code>optional int32 vHead = 9;</code>
     */
    public boolean hasVHead() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 vHead = 9;</code>
     */
    public int getVHead() {
      return vHead_;
    }

    // optional int32 packetSize = 10;
    public static final int PACKETSIZE_FIELD_NUMBER = 10;
    private int packetSize_;
    /**
     * <code>optional int32 packetSize = 10;</code>
     */
    public boolean hasPacketSize() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int32 packetSize = 10;</code>
     */
    public int getPacketSize() {
      return packetSize_;
    }

    // optional int32 secrect = 11;
    public static final int SECRECT_FIELD_NUMBER = 11;
    private int secrect_;
    /**
     * <code>optional int32 secrect = 11;</code>
     */
    public boolean hasSecrect() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional int32 secrect = 11;</code>
     */
    public int getSecrect() {
      return secrect_;
    }

    // optional int32 tempID = 12;
    public static final int TEMPID_FIELD_NUMBER = 12;
    private int tempID_;
    /**
     * <code>optional int32 tempID = 12;</code>
     */
    public boolean hasTempID() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional int32 tempID = 12;</code>
     */
    public int getTempID() {
      return tempID_;
    }

    // optional int32 timeStamp = 13;
    public static final int TIMESTAMP_FIELD_NUMBER = 13;
    private int timeStamp_;
    /**
     * <code>optional int32 timeStamp = 13;</code>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>optional int32 timeStamp = 13;</code>
     */
    public int getTimeStamp() {
      return timeStamp_;
    }

    // optional int32 version = 14;
    public static final int VERSION_FIELD_NUMBER = 14;
    private int version_;
    /**
     * <code>optional int32 version = 14;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00002000) == 0x00002000);
    }
    /**
     * <code>optional int32 version = 14;</code>
     */
    public int getVersion() {
      return version_;
    }

    // optional bool zip = 15;
    public static final int ZIP_FIELD_NUMBER = 15;
    private boolean zip_;
    /**
     * <code>optional bool zip = 15;</code>
     */
    public boolean hasZip() {
      return ((bitField0_ & 0x00004000) == 0x00004000);
    }
    /**
     * <code>optional bool zip = 15;</code>
     */
    public boolean getZip() {
      return zip_;
    }

    // optional string toUser = 16;
    public static final int TOUSER_FIELD_NUMBER = 16;
    private java.lang.Object toUser_;
    /**
     * <code>optional string toUser = 16;</code>
     */
    public boolean hasToUser() {
      return ((bitField0_ & 0x00008000) == 0x00008000);
    }
    /**
     * <code>optional string toUser = 16;</code>
     */
    public java.lang.String getToUser() {
      java.lang.Object ref = toUser_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          toUser_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string toUser = 16;</code>
     */
    public com.google.protobuf.ByteString
        getToUserBytes() {
      java.lang.Object ref = toUser_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string traceID = 17;
    public static final int TRACEID_FIELD_NUMBER = 17;
    private java.lang.Object traceID_;
    /**
     * <code>optional string traceID = 17;</code>
     */
    public boolean hasTraceID() {
      return ((bitField0_ & 0x00010000) == 0x00010000);
    }
    /**
     * <code>optional string traceID = 17;</code>
     */
    public java.lang.String getTraceID() {
      java.lang.Object ref = traceID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          traceID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string traceID = 17;</code>
     */
    public com.google.protobuf.ByteString
        getTraceIDBytes() {
      java.lang.Object ref = traceID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        traceID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      cmsgID_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
      from_ = "";
      messageId_ = 0;
      messageServiceType_ = 0;
      messageType_ = 0;
      messageFlag_ = 0;
      appID_ = 0;
      vHead_ = 0;
      packetSize_ = 0;
      secrect_ = 0;
      tempID_ = 0;
      timeStamp_ = 0;
      version_ = 0;
      zip_ = false;
      toUser_ = "";
      traceID_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCmsgIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, content_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getFromBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, messageId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, messageServiceType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, messageType_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, messageFlag_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, appID_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, vHead_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, packetSize_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, secrect_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeInt32(12, tempID_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, timeStamp_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        output.writeInt32(14, version_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        output.writeBool(15, zip_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        output.writeBytes(16, getToUserBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        output.writeBytes(17, getTraceIDBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCmsgIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, content_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getFromBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, messageId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, messageServiceType_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, messageType_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, messageFlag_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, appID_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, vHead_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, packetSize_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, secrect_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, tempID_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, timeStamp_);
      }
      if (((bitField0_ & 0x00002000) == 0x00002000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(14, version_);
      }
      if (((bitField0_ & 0x00004000) == 0x00004000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(15, zip_);
      }
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(16, getToUserBytes());
      }
      if (((bitField0_ & 0x00010000) == 0x00010000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(17, getTraceIDBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TextMessagePacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.handwin.serializable.module.TextMessagePacketPro.internal_static_TextMessagePacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.handwin.serializable.module.TextMessagePacketPro.internal_static_TextMessagePacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket.class, com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket.Builder.class);
      }

      // Construct using com.handwin.serializable.TextMessagePacketPro.TextMessagePacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cmsgID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        from_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        messageId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        messageServiceType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        messageType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        messageFlag_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        appID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        vHead_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        packetSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        secrect_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        tempID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000800);
        timeStamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00002000);
        zip_ = false;
        bitField0_ = (bitField0_ & ~0x00004000);
        toUser_ = "";
        bitField0_ = (bitField0_ & ~0x00008000);
        traceID_ = "";
        bitField0_ = (bitField0_ & ~0x00010000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.handwin.serializable.module.TextMessagePacketPro.internal_static_TextMessagePacket_descriptor;
      }

      public com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket getDefaultInstanceForType() {
        return com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket.getDefaultInstance();
      }

      public com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket build() {
        com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket buildPartial() {
        com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket result = new com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cmsgID_ = cmsgID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.from_ = from_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.messageId_ = messageId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.messageServiceType_ = messageServiceType_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.messageFlag_ = messageFlag_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.appID_ = appID_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.vHead_ = vHead_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.packetSize_ = packetSize_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.secrect_ = secrect_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.tempID_ = tempID_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.timeStamp_ = timeStamp_;
        if (((from_bitField0_ & 0x00002000) == 0x00002000)) {
          to_bitField0_ |= 0x00002000;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00004000) == 0x00004000)) {
          to_bitField0_ |= 0x00004000;
        }
        result.zip_ = zip_;
        if (((from_bitField0_ & 0x00008000) == 0x00008000)) {
          to_bitField0_ |= 0x00008000;
        }
        result.toUser_ = toUser_;
        if (((from_bitField0_ & 0x00010000) == 0x00010000)) {
          to_bitField0_ |= 0x00010000;
        }
        result.traceID_ = traceID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket) {
          return mergeFrom((com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket other) {
        if (other == com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket.getDefaultInstance()) return this;
        if (other.hasCmsgID()) {
          bitField0_ |= 0x00000001;
          cmsgID_ = other.cmsgID_;
          onChanged();
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        if (other.hasFrom()) {
          bitField0_ |= 0x00000004;
          from_ = other.from_;
          onChanged();
        }
        if (other.hasMessageId()) {
          setMessageId(other.getMessageId());
        }
        if (other.hasMessageServiceType()) {
          setMessageServiceType(other.getMessageServiceType());
        }
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasMessageFlag()) {
          setMessageFlag(other.getMessageFlag());
        }
        if (other.hasAppID()) {
          setAppID(other.getAppID());
        }
        if (other.hasVHead()) {
          setVHead(other.getVHead());
        }
        if (other.hasPacketSize()) {
          setPacketSize(other.getPacketSize());
        }
        if (other.hasSecrect()) {
          setSecrect(other.getSecrect());
        }
        if (other.hasTempID()) {
          setTempID(other.getTempID());
        }
        if (other.hasTimeStamp()) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasZip()) {
          setZip(other.getZip());
        }
        if (other.hasToUser()) {
          bitField0_ |= 0x00008000;
          toUser_ = other.toUser_;
          onChanged();
        }
        if (other.hasTraceID()) {
          bitField0_ |= 0x00010000;
          traceID_ = other.traceID_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.handwin.serializable.module.TextMessagePacketPro.TextMessagePacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string cmsgID = 1;
      private java.lang.Object cmsgID_ = "";
      /**
       * <code>optional string cmsgID = 1;</code>
       */
      public boolean hasCmsgID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string cmsgID = 1;</code>
       */
      public java.lang.String getCmsgID() {
        java.lang.Object ref = cmsgID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          cmsgID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cmsgID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCmsgIDBytes() {
        java.lang.Object ref = cmsgID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmsgID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cmsgID = 1;</code>
       */
      public Builder setCmsgID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        cmsgID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cmsgID = 1;</code>
       */
      public Builder clearCmsgID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmsgID_ = getDefaultInstance().getCmsgID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cmsgID = 1;</code>
       */
      public Builder setCmsgIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        cmsgID_ = value;
        onChanged();
        return this;
      }

      // optional bytes content = 2;
      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes content = 2;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes content = 2;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>optional bytes content = 2;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes content = 2;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      // optional string from = 3;
      private java.lang.Object from_ = "";
      /**
       * <code>optional string from = 3;</code>
       */
      public boolean hasFrom() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string from = 3;</code>
       */
      public java.lang.String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string from = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFromBytes() {
        java.lang.Object ref = from_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          from_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string from = 3;</code>
       */
      public Builder setFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string from = 3;</code>
       */
      public Builder clearFrom() {
        bitField0_ = (bitField0_ & ~0x00000004);
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      /**
       * <code>optional string from = 3;</code>
       */
      public Builder setFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        from_ = value;
        onChanged();
        return this;
      }

      // optional int32 messageId = 4;
      private int messageId_ ;
      /**
       * <code>optional int32 messageId = 4;</code>
       */
      public boolean hasMessageId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 messageId = 4;</code>
       */
      public int getMessageId() {
        return messageId_;
      }
      /**
       * <code>optional int32 messageId = 4;</code>
       */
      public Builder setMessageId(int value) {
        bitField0_ |= 0x00000008;
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 messageId = 4;</code>
       */
      public Builder clearMessageId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        messageId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 messageServiceType = 5;
      private int messageServiceType_ ;
      /**
       * <code>optional int32 messageServiceType = 5;</code>
       */
      public boolean hasMessageServiceType() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 messageServiceType = 5;</code>
       */
      public int getMessageServiceType() {
        return messageServiceType_;
      }
      /**
       * <code>optional int32 messageServiceType = 5;</code>
       */
      public Builder setMessageServiceType(int value) {
        bitField0_ |= 0x00000010;
        messageServiceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 messageServiceType = 5;</code>
       */
      public Builder clearMessageServiceType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        messageServiceType_ = 0;
        onChanged();
        return this;
      }

      // optional int32 messageType = 6;
      private int messageType_ ;
      /**
       * <code>optional int32 messageType = 6;</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 messageType = 6;</code>
       */
      public int getMessageType() {
        return messageType_;
      }
      /**
       * <code>optional int32 messageType = 6;</code>
       */
      public Builder setMessageType(int value) {
        bitField0_ |= 0x00000020;
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 messageType = 6;</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        messageType_ = 0;
        onChanged();
        return this;
      }

      // optional int32 messageFlag = 7;
      private int messageFlag_ ;
      /**
       * <code>optional int32 messageFlag = 7;</code>
       */
      public boolean hasMessageFlag() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 messageFlag = 7;</code>
       */
      public int getMessageFlag() {
        return messageFlag_;
      }
      /**
       * <code>optional int32 messageFlag = 7;</code>
       */
      public Builder setMessageFlag(int value) {
        bitField0_ |= 0x00000040;
        messageFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 messageFlag = 7;</code>
       */
      public Builder clearMessageFlag() {
        bitField0_ = (bitField0_ & ~0x00000040);
        messageFlag_ = 0;
        onChanged();
        return this;
      }

      // optional int32 appID = 8;
      private int appID_ ;
      /**
       * <code>optional int32 appID = 8;</code>
       */
      public boolean hasAppID() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 appID = 8;</code>
       */
      public int getAppID() {
        return appID_;
      }
      /**
       * <code>optional int32 appID = 8;</code>
       */
      public Builder setAppID(int value) {
        bitField0_ |= 0x00000080;
        appID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 appID = 8;</code>
       */
      public Builder clearAppID() {
        bitField0_ = (bitField0_ & ~0x00000080);
        appID_ = 0;
        onChanged();
        return this;
      }

      // optional int32 vHead = 9;
      private int vHead_ ;
      /**
       * <code>optional int32 vHead = 9;</code>
       */
      public boolean hasVHead() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 vHead = 9;</code>
       */
      public int getVHead() {
        return vHead_;
      }
      /**
       * <code>optional int32 vHead = 9;</code>
       */
      public Builder setVHead(int value) {
        bitField0_ |= 0x00000100;
        vHead_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 vHead = 9;</code>
       */
      public Builder clearVHead() {
        bitField0_ = (bitField0_ & ~0x00000100);
        vHead_ = 0;
        onChanged();
        return this;
      }

      // optional int32 packetSize = 10;
      private int packetSize_ ;
      /**
       * <code>optional int32 packetSize = 10;</code>
       */
      public boolean hasPacketSize() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int32 packetSize = 10;</code>
       */
      public int getPacketSize() {
        return packetSize_;
      }
      /**
       * <code>optional int32 packetSize = 10;</code>
       */
      public Builder setPacketSize(int value) {
        bitField0_ |= 0x00000200;
        packetSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 packetSize = 10;</code>
       */
      public Builder clearPacketSize() {
        bitField0_ = (bitField0_ & ~0x00000200);
        packetSize_ = 0;
        onChanged();
        return this;
      }

      // optional int32 secrect = 11;
      private int secrect_ ;
      /**
       * <code>optional int32 secrect = 11;</code>
       */
      public boolean hasSecrect() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional int32 secrect = 11;</code>
       */
      public int getSecrect() {
        return secrect_;
      }
      /**
       * <code>optional int32 secrect = 11;</code>
       */
      public Builder setSecrect(int value) {
        bitField0_ |= 0x00000400;
        secrect_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 secrect = 11;</code>
       */
      public Builder clearSecrect() {
        bitField0_ = (bitField0_ & ~0x00000400);
        secrect_ = 0;
        onChanged();
        return this;
      }

      // optional int32 tempID = 12;
      private int tempID_ ;
      /**
       * <code>optional int32 tempID = 12;</code>
       */
      public boolean hasTempID() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional int32 tempID = 12;</code>
       */
      public int getTempID() {
        return tempID_;
      }
      /**
       * <code>optional int32 tempID = 12;</code>
       */
      public Builder setTempID(int value) {
        bitField0_ |= 0x00000800;
        tempID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 tempID = 12;</code>
       */
      public Builder clearTempID() {
        bitField0_ = (bitField0_ & ~0x00000800);
        tempID_ = 0;
        onChanged();
        return this;
      }

      // optional int32 timeStamp = 13;
      private int timeStamp_ ;
      /**
       * <code>optional int32 timeStamp = 13;</code>
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>optional int32 timeStamp = 13;</code>
       */
      public int getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>optional int32 timeStamp = 13;</code>
       */
      public Builder setTimeStamp(int value) {
        bitField0_ |= 0x00001000;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 timeStamp = 13;</code>
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00001000);
        timeStamp_ = 0;
        onChanged();
        return this;
      }

      // optional int32 version = 14;
      private int version_ ;
      /**
       * <code>optional int32 version = 14;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00002000) == 0x00002000);
      }
      /**
       * <code>optional int32 version = 14;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>optional int32 version = 14;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00002000;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 version = 14;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00002000);
        version_ = 0;
        onChanged();
        return this;
      }

      // optional bool zip = 15;
      private boolean zip_ ;
      /**
       * <code>optional bool zip = 15;</code>
       */
      public boolean hasZip() {
        return ((bitField0_ & 0x00004000) == 0x00004000);
      }
      /**
       * <code>optional bool zip = 15;</code>
       */
      public boolean getZip() {
        return zip_;
      }
      /**
       * <code>optional bool zip = 15;</code>
       */
      public Builder setZip(boolean value) {
        bitField0_ |= 0x00004000;
        zip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool zip = 15;</code>
       */
      public Builder clearZip() {
        bitField0_ = (bitField0_ & ~0x00004000);
        zip_ = false;
        onChanged();
        return this;
      }

      // optional string toUser = 16;
      private java.lang.Object toUser_ = "";
      /**
       * <code>optional string toUser = 16;</code>
       */
      public boolean hasToUser() {
        return ((bitField0_ & 0x00008000) == 0x00008000);
      }
      /**
       * <code>optional string toUser = 16;</code>
       */
      public java.lang.String getToUser() {
        java.lang.Object ref = toUser_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          toUser_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string toUser = 16;</code>
       */
      public com.google.protobuf.ByteString
          getToUserBytes() {
        java.lang.Object ref = toUser_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toUser_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string toUser = 16;</code>
       */
      public Builder setToUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        toUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string toUser = 16;</code>
       */
      public Builder clearToUser() {
        bitField0_ = (bitField0_ & ~0x00008000);
        toUser_ = getDefaultInstance().getToUser();
        onChanged();
        return this;
      }
      /**
       * <code>optional string toUser = 16;</code>
       */
      public Builder setToUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00008000;
        toUser_ = value;
        onChanged();
        return this;
      }

      // optional string traceID = 17;
      private java.lang.Object traceID_ = "";
      /**
       * <code>optional string traceID = 17;</code>
       */
      public boolean hasTraceID() {
        return ((bitField0_ & 0x00010000) == 0x00010000);
      }
      /**
       * <code>optional string traceID = 17;</code>
       */
      public java.lang.String getTraceID() {
        java.lang.Object ref = traceID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          traceID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string traceID = 17;</code>
       */
      public com.google.protobuf.ByteString
          getTraceIDBytes() {
        java.lang.Object ref = traceID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          traceID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string traceID = 17;</code>
       */
      public Builder setTraceID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        traceID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string traceID = 17;</code>
       */
      public Builder clearTraceID() {
        bitField0_ = (bitField0_ & ~0x00010000);
        traceID_ = getDefaultInstance().getTraceID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string traceID = 17;</code>
       */
      public Builder setTraceIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00010000;
        traceID_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:TextMessagePacket)
    }

    static {
      defaultInstance = new TextMessagePacket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:TextMessagePacket)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TextMessagePacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TextMessagePacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017message_pro.pro\"\300\002\n\021TextMessagePacket\022" +
      "\016\n\006cmsgID\030\001 \001(\t\022\017\n\007content\030\002 \001(\014\022\014\n\004from" +
      "\030\003 \001(\t\022\021\n\tmessageId\030\004 \001(\005\022\032\n\022messageServ" +
      "iceType\030\005 \001(\005\022\023\n\013messageType\030\006 \001(\005\022\023\n\013me" +
      "ssageFlag\030\007 \001(\005\022\r\n\005appID\030\010 \001(\005\022\r\n\005vHead\030" +
      "\t \001(\005\022\022\n\npacketSize\030\n \001(\005\022\017\n\007secrect\030\013 \001" +
      "(\005\022\016\n\006tempID\030\014 \001(\005\022\021\n\ttimeStamp\030\r \001(\005\022\017\n" +
      "\007version\030\016 \001(\005\022\013\n\003zip\030\017 \001(\010\022\016\n\006toUser\030\020 " +
      "\001(\t\022\017\n\007traceID\030\021 \001(\tB0\n\030com.handwin.seri" +
      "alizableB\024TextMessagePacketPro"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_TextMessagePacket_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_TextMessagePacket_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TextMessagePacket_descriptor,
              new java.lang.String[] { "CmsgID", "Content", "From", "MessageId", "MessageServiceType", "MessageType", "MessageFlag", "AppID", "VHead", "PacketSize", "Secrect", "TempID", "TimeStamp", "Version", "Zip", "ToUser", "TraceID", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
