/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.handwin.serializable.module;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TextMessagePacketAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TextMessagePacketAvro\",\"namespace\":\"com.handwin.serializable\",\"fields\":[{\"name\":\"cmsgID\",\"type\":[\"string\",\"null\"]},{\"name\":\"content\",\"type\":[\"bytes\",\"null\"]},{\"name\":\"from\",\"type\":[\"bytes\",\"null\"]},{\"name\":\"messageId\",\"type\":[\"long\",\"null\"]},{\"name\":\"messageServiceType\",\"type\":\"int\"},{\"name\":\"messageType\",\"type\":\"int\"},{\"name\":\"messageFlag\",\"type\":\"int\"},{\"name\":\"appID\",\"type\":\"int\"},{\"name\":\"vHead\",\"type\":\"int\"},{\"name\":\"packetSize\",\"type\":\"int\"},{\"name\":\"secrect\",\"type\":\"int\"},{\"name\":\"tempID\",\"type\":\"int\"},{\"name\":\"timeStamp\",\"type\":\"long\"},{\"name\":\"version\",\"type\":\"long\"},{\"name\":\"zip\",\"type\":\"boolean\"},{\"name\":\"toUser\",\"type\":[\"string\",\"null\"]},{\"name\":\"traceID\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence cmsgID;
  @Deprecated public java.nio.ByteBuffer content;
  @Deprecated public java.nio.ByteBuffer from;
  @Deprecated public java.lang.Long messageId;
  @Deprecated public int messageServiceType;
  @Deprecated public int messageType;
  @Deprecated public int messageFlag;
  @Deprecated public int appID;
  @Deprecated public int vHead;
  @Deprecated public int packetSize;
  @Deprecated public int secrect;
  @Deprecated public int tempID;
  @Deprecated public long timeStamp;
  @Deprecated public long version;
  @Deprecated public boolean zip;
  @Deprecated public java.lang.CharSequence toUser;
  @Deprecated public int traceID;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public TextMessagePacketAvro() {}

  /**
   * All-args constructor.
   */
  public TextMessagePacketAvro(java.lang.CharSequence cmsgID, java.nio.ByteBuffer content, java.nio.ByteBuffer from, java.lang.Long messageId, java.lang.Integer messageServiceType, java.lang.Integer messageType, java.lang.Integer messageFlag, java.lang.Integer appID, java.lang.Integer vHead, java.lang.Integer packetSize, java.lang.Integer secrect, java.lang.Integer tempID, java.lang.Long timeStamp, java.lang.Long version, java.lang.Boolean zip, java.lang.CharSequence toUser, java.lang.Integer traceID) {
    this.cmsgID = cmsgID;
    this.content = content;
    this.from = from;
    this.messageId = messageId;
    this.messageServiceType = messageServiceType;
    this.messageType = messageType;
    this.messageFlag = messageFlag;
    this.appID = appID;
    this.vHead = vHead;
    this.packetSize = packetSize;
    this.secrect = secrect;
    this.tempID = tempID;
    this.timeStamp = timeStamp;
    this.version = version;
    this.zip = zip;
    this.toUser = toUser;
    this.traceID = traceID;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return cmsgID;
    case 1: return content;
    case 2: return from;
    case 3: return messageId;
    case 4: return messageServiceType;
    case 5: return messageType;
    case 6: return messageFlag;
    case 7: return appID;
    case 8: return vHead;
    case 9: return packetSize;
    case 10: return secrect;
    case 11: return tempID;
    case 12: return timeStamp;
    case 13: return version;
    case 14: return zip;
    case 15: return toUser;
    case 16: return traceID;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: cmsgID = (java.lang.CharSequence)value$; break;
    case 1: content = (java.nio.ByteBuffer)value$; break;
    case 2: from = (java.nio.ByteBuffer)value$; break;
    case 3: messageId = (java.lang.Long)value$; break;
    case 4: messageServiceType = (java.lang.Integer)value$; break;
    case 5: messageType = (java.lang.Integer)value$; break;
    case 6: messageFlag = (java.lang.Integer)value$; break;
    case 7: appID = (java.lang.Integer)value$; break;
    case 8: vHead = (java.lang.Integer)value$; break;
    case 9: packetSize = (java.lang.Integer)value$; break;
    case 10: secrect = (java.lang.Integer)value$; break;
    case 11: tempID = (java.lang.Integer)value$; break;
    case 12: timeStamp = (java.lang.Long)value$; break;
    case 13: version = (java.lang.Long)value$; break;
    case 14: zip = (java.lang.Boolean)value$; break;
    case 15: toUser = (java.lang.CharSequence)value$; break;
    case 16: traceID = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'cmsgID' field.
   */
  public java.lang.CharSequence getCmsgID() {
    return cmsgID;
  }

  /**
   * Sets the value of the 'cmsgID' field.
   * @param value the value to set.
   */
  public void setCmsgID(java.lang.CharSequence value) {
    this.cmsgID = value;
  }

  /**
   * Gets the value of the 'content' field.
   */
  public java.nio.ByteBuffer getContent() {
    return content;
  }

  /**
   * Sets the value of the 'content' field.
   * @param value the value to set.
   */
  public void setContent(java.nio.ByteBuffer value) {
    this.content = value;
  }

  /**
   * Gets the value of the 'from' field.
   */
  public java.nio.ByteBuffer getFrom() {
    return from;
  }

  /**
   * Sets the value of the 'from' field.
   * @param value the value to set.
   */
  public void setFrom(java.nio.ByteBuffer value) {
    this.from = value;
  }

  /**
   * Gets the value of the 'messageId' field.
   */
  public java.lang.Long getMessageId() {
    return messageId;
  }

  /**
   * Sets the value of the 'messageId' field.
   * @param value the value to set.
   */
  public void setMessageId(java.lang.Long value) {
    this.messageId = value;
  }

  /**
   * Gets the value of the 'messageServiceType' field.
   */
  public java.lang.Integer getMessageServiceType() {
    return messageServiceType;
  }

  /**
   * Sets the value of the 'messageServiceType' field.
   * @param value the value to set.
   */
  public void setMessageServiceType(java.lang.Integer value) {
    this.messageServiceType = value;
  }

  /**
   * Gets the value of the 'messageType' field.
   */
  public java.lang.Integer getMessageType() {
    return messageType;
  }

  /**
   * Sets the value of the 'messageType' field.
   * @param value the value to set.
   */
  public void setMessageType(java.lang.Integer value) {
    this.messageType = value;
  }

  /**
   * Gets the value of the 'messageFlag' field.
   */
  public java.lang.Integer getMessageFlag() {
    return messageFlag;
  }

  /**
   * Sets the value of the 'messageFlag' field.
   * @param value the value to set.
   */
  public void setMessageFlag(java.lang.Integer value) {
    this.messageFlag = value;
  }

  /**
   * Gets the value of the 'appID' field.
   */
  public java.lang.Integer getAppID() {
    return appID;
  }

  /**
   * Sets the value of the 'appID' field.
   * @param value the value to set.
   */
  public void setAppID(java.lang.Integer value) {
    this.appID = value;
  }

  /**
   * Gets the value of the 'vHead' field.
   */
  public java.lang.Integer getVHead() {
    return vHead;
  }

  /**
   * Sets the value of the 'vHead' field.
   * @param value the value to set.
   */
  public void setVHead(java.lang.Integer value) {
    this.vHead = value;
  }

  /**
   * Gets the value of the 'packetSize' field.
   */
  public java.lang.Integer getPacketSize() {
    return packetSize;
  }

  /**
   * Sets the value of the 'packetSize' field.
   * @param value the value to set.
   */
  public void setPacketSize(java.lang.Integer value) {
    this.packetSize = value;
  }

  /**
   * Gets the value of the 'secrect' field.
   */
  public java.lang.Integer getSecrect() {
    return secrect;
  }

  /**
   * Sets the value of the 'secrect' field.
   * @param value the value to set.
   */
  public void setSecrect(java.lang.Integer value) {
    this.secrect = value;
  }

  /**
   * Gets the value of the 'tempID' field.
   */
  public java.lang.Integer getTempID() {
    return tempID;
  }

  /**
   * Sets the value of the 'tempID' field.
   * @param value the value to set.
   */
  public void setTempID(java.lang.Integer value) {
    this.tempID = value;
  }

  /**
   * Gets the value of the 'timeStamp' field.
   */
  public java.lang.Long getTimeStamp() {
    return timeStamp;
  }

  /**
   * Sets the value of the 'timeStamp' field.
   * @param value the value to set.
   */
  public void setTimeStamp(java.lang.Long value) {
    this.timeStamp = value;
  }

  /**
   * Gets the value of the 'version' field.
   */
  public java.lang.Long getVersion() {
    return version;
  }

  /**
   * Sets the value of the 'version' field.
   * @param value the value to set.
   */
  public void setVersion(java.lang.Long value) {
    this.version = value;
  }

  /**
   * Gets the value of the 'zip' field.
   */
  public java.lang.Boolean getZip() {
    return zip;
  }

  /**
   * Sets the value of the 'zip' field.
   * @param value the value to set.
   */
  public void setZip(java.lang.Boolean value) {
    this.zip = value;
  }

  /**
   * Gets the value of the 'toUser' field.
   */
  public java.lang.CharSequence getToUser() {
    return toUser;
  }

  /**
   * Sets the value of the 'toUser' field.
   * @param value the value to set.
   */
  public void setToUser(java.lang.CharSequence value) {
    this.toUser = value;
  }

  /**
   * Gets the value of the 'traceID' field.
   */
  public java.lang.Integer getTraceID() {
    return traceID;
  }

  /**
   * Sets the value of the 'traceID' field.
   * @param value the value to set.
   */
  public void setTraceID(java.lang.Integer value) {
    this.traceID = value;
  }

  /** Creates a new TextMessagePacketAvro RecordBuilder */
  public static com.handwin.serializable.module.TextMessagePacketAvro.Builder newBuilder() {
    return new com.handwin.serializable.module.TextMessagePacketAvro.Builder();
  }
  
  /** Creates a new TextMessagePacketAvro RecordBuilder by copying an existing Builder */
  public static com.handwin.serializable.module.TextMessagePacketAvro.Builder newBuilder(com.handwin.serializable.module.TextMessagePacketAvro.Builder other) {
    return new com.handwin.serializable.module.TextMessagePacketAvro.Builder(other);
  }
  
  /** Creates a new TextMessagePacketAvro RecordBuilder by copying an existing TextMessagePacketAvro instance */
  public static com.handwin.serializable.module.TextMessagePacketAvro.Builder newBuilder(com.handwin.serializable.module.TextMessagePacketAvro other) {
    return new com.handwin.serializable.module.TextMessagePacketAvro.Builder(other);
  }
  
  /**
   * RecordBuilder for TextMessagePacketAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TextMessagePacketAvro>
    implements org.apache.avro.data.RecordBuilder<TextMessagePacketAvro> {

    private java.lang.CharSequence cmsgID;
    private java.nio.ByteBuffer content;
    private java.nio.ByteBuffer from;
    private java.lang.Long messageId;
    private int messageServiceType;
    private int messageType;
    private int messageFlag;
    private int appID;
    private int vHead;
    private int packetSize;
    private int secrect;
    private int tempID;
    private long timeStamp;
    private long version;
    private boolean zip;
    private java.lang.CharSequence toUser;
    private int traceID;

    /** Creates a new Builder */
    private Builder() {
      super(com.handwin.serializable.module.TextMessagePacketAvro.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.handwin.serializable.module.TextMessagePacketAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.cmsgID)) {
        this.cmsgID = data().deepCopy(fields()[0].schema(), other.cmsgID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.content)) {
        this.content = data().deepCopy(fields()[1].schema(), other.content);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.from)) {
        this.from = data().deepCopy(fields()[2].schema(), other.from);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.messageId)) {
        this.messageId = data().deepCopy(fields()[3].schema(), other.messageId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.messageServiceType)) {
        this.messageServiceType = data().deepCopy(fields()[4].schema(), other.messageServiceType);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.messageType)) {
        this.messageType = data().deepCopy(fields()[5].schema(), other.messageType);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.messageFlag)) {
        this.messageFlag = data().deepCopy(fields()[6].schema(), other.messageFlag);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.appID)) {
        this.appID = data().deepCopy(fields()[7].schema(), other.appID);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.vHead)) {
        this.vHead = data().deepCopy(fields()[8].schema(), other.vHead);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.packetSize)) {
        this.packetSize = data().deepCopy(fields()[9].schema(), other.packetSize);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.secrect)) {
        this.secrect = data().deepCopy(fields()[10].schema(), other.secrect);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.tempID)) {
        this.tempID = data().deepCopy(fields()[11].schema(), other.tempID);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.timeStamp)) {
        this.timeStamp = data().deepCopy(fields()[12].schema(), other.timeStamp);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.version)) {
        this.version = data().deepCopy(fields()[13].schema(), other.version);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.zip)) {
        this.zip = data().deepCopy(fields()[14].schema(), other.zip);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.toUser)) {
        this.toUser = data().deepCopy(fields()[15].schema(), other.toUser);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.traceID)) {
        this.traceID = data().deepCopy(fields()[16].schema(), other.traceID);
        fieldSetFlags()[16] = true;
      }
    }
    
    /** Creates a Builder by copying an existing TextMessagePacketAvro instance */
    private Builder(com.handwin.serializable.module.TextMessagePacketAvro other) {
            super(com.handwin.serializable.module.TextMessagePacketAvro.SCHEMA$);
      if (isValidValue(fields()[0], other.cmsgID)) {
        this.cmsgID = data().deepCopy(fields()[0].schema(), other.cmsgID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.content)) {
        this.content = data().deepCopy(fields()[1].schema(), other.content);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.from)) {
        this.from = data().deepCopy(fields()[2].schema(), other.from);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.messageId)) {
        this.messageId = data().deepCopy(fields()[3].schema(), other.messageId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.messageServiceType)) {
        this.messageServiceType = data().deepCopy(fields()[4].schema(), other.messageServiceType);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.messageType)) {
        this.messageType = data().deepCopy(fields()[5].schema(), other.messageType);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.messageFlag)) {
        this.messageFlag = data().deepCopy(fields()[6].schema(), other.messageFlag);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.appID)) {
        this.appID = data().deepCopy(fields()[7].schema(), other.appID);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.vHead)) {
        this.vHead = data().deepCopy(fields()[8].schema(), other.vHead);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.packetSize)) {
        this.packetSize = data().deepCopy(fields()[9].schema(), other.packetSize);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.secrect)) {
        this.secrect = data().deepCopy(fields()[10].schema(), other.secrect);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.tempID)) {
        this.tempID = data().deepCopy(fields()[11].schema(), other.tempID);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.timeStamp)) {
        this.timeStamp = data().deepCopy(fields()[12].schema(), other.timeStamp);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.version)) {
        this.version = data().deepCopy(fields()[13].schema(), other.version);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.zip)) {
        this.zip = data().deepCopy(fields()[14].schema(), other.zip);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.toUser)) {
        this.toUser = data().deepCopy(fields()[15].schema(), other.toUser);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.traceID)) {
        this.traceID = data().deepCopy(fields()[16].schema(), other.traceID);
        fieldSetFlags()[16] = true;
      }
    }

    /** Gets the value of the 'cmsgID' field */
    public java.lang.CharSequence getCmsgID() {
      return cmsgID;
    }
    
    /** Sets the value of the 'cmsgID' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder setCmsgID(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.cmsgID = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'cmsgID' field has been set */
    public boolean hasCmsgID() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'cmsgID' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder clearCmsgID() {
      cmsgID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'content' field */
    public java.nio.ByteBuffer getContent() {
      return content;
    }
    
    /** Sets the value of the 'content' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder setContent(java.nio.ByteBuffer value) {
      validate(fields()[1], value);
      this.content = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'content' field has been set */
    public boolean hasContent() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'content' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder clearContent() {
      content = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'from' field */
    public java.nio.ByteBuffer getFrom() {
      return from;
    }
    
    /** Sets the value of the 'from' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder setFrom(java.nio.ByteBuffer value) {
      validate(fields()[2], value);
      this.from = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'from' field has been set */
    public boolean hasFrom() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'from' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder clearFrom() {
      from = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'messageId' field */
    public java.lang.Long getMessageId() {
      return messageId;
    }
    
    /** Sets the value of the 'messageId' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder setMessageId(java.lang.Long value) {
      validate(fields()[3], value);
      this.messageId = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'messageId' field has been set */
    public boolean hasMessageId() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'messageId' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder clearMessageId() {
      messageId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'messageServiceType' field */
    public java.lang.Integer getMessageServiceType() {
      return messageServiceType;
    }
    
    /** Sets the value of the 'messageServiceType' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder setMessageServiceType(int value) {
      validate(fields()[4], value);
      this.messageServiceType = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'messageServiceType' field has been set */
    public boolean hasMessageServiceType() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'messageServiceType' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder clearMessageServiceType() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'messageType' field */
    public java.lang.Integer getMessageType() {
      return messageType;
    }
    
    /** Sets the value of the 'messageType' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder setMessageType(int value) {
      validate(fields()[5], value);
      this.messageType = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'messageType' field has been set */
    public boolean hasMessageType() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'messageType' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder clearMessageType() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'messageFlag' field */
    public java.lang.Integer getMessageFlag() {
      return messageFlag;
    }
    
    /** Sets the value of the 'messageFlag' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder setMessageFlag(int value) {
      validate(fields()[6], value);
      this.messageFlag = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'messageFlag' field has been set */
    public boolean hasMessageFlag() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'messageFlag' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder clearMessageFlag() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'appID' field */
    public java.lang.Integer getAppID() {
      return appID;
    }
    
    /** Sets the value of the 'appID' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder setAppID(int value) {
      validate(fields()[7], value);
      this.appID = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'appID' field has been set */
    public boolean hasAppID() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'appID' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder clearAppID() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'vHead' field */
    public java.lang.Integer getVHead() {
      return vHead;
    }
    
    /** Sets the value of the 'vHead' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder setVHead(int value) {
      validate(fields()[8], value);
      this.vHead = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'vHead' field has been set */
    public boolean hasVHead() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'vHead' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder clearVHead() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'packetSize' field */
    public java.lang.Integer getPacketSize() {
      return packetSize;
    }
    
    /** Sets the value of the 'packetSize' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder setPacketSize(int value) {
      validate(fields()[9], value);
      this.packetSize = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'packetSize' field has been set */
    public boolean hasPacketSize() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'packetSize' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder clearPacketSize() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'secrect' field */
    public java.lang.Integer getSecrect() {
      return secrect;
    }
    
    /** Sets the value of the 'secrect' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder setSecrect(int value) {
      validate(fields()[10], value);
      this.secrect = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'secrect' field has been set */
    public boolean hasSecrect() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'secrect' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder clearSecrect() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'tempID' field */
    public java.lang.Integer getTempID() {
      return tempID;
    }
    
    /** Sets the value of the 'tempID' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder setTempID(int value) {
      validate(fields()[11], value);
      this.tempID = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'tempID' field has been set */
    public boolean hasTempID() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'tempID' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder clearTempID() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'timeStamp' field */
    public java.lang.Long getTimeStamp() {
      return timeStamp;
    }
    
    /** Sets the value of the 'timeStamp' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder setTimeStamp(long value) {
      validate(fields()[12], value);
      this.timeStamp = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'timeStamp' field has been set */
    public boolean hasTimeStamp() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'timeStamp' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder clearTimeStamp() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'version' field */
    public java.lang.Long getVersion() {
      return version;
    }
    
    /** Sets the value of the 'version' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder setVersion(long value) {
      validate(fields()[13], value);
      this.version = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'version' field has been set */
    public boolean hasVersion() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'version' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder clearVersion() {
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'zip' field */
    public java.lang.Boolean getZip() {
      return zip;
    }
    
    /** Sets the value of the 'zip' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder setZip(boolean value) {
      validate(fields()[14], value);
      this.zip = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'zip' field has been set */
    public boolean hasZip() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'zip' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder clearZip() {
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'toUser' field */
    public java.lang.CharSequence getToUser() {
      return toUser;
    }
    
    /** Sets the value of the 'toUser' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder setToUser(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.toUser = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'toUser' field has been set */
    public boolean hasToUser() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'toUser' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder clearToUser() {
      toUser = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'traceID' field */
    public java.lang.Integer getTraceID() {
      return traceID;
    }
    
    /** Sets the value of the 'traceID' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder setTraceID(int value) {
      validate(fields()[16], value);
      this.traceID = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'traceID' field has been set */
    public boolean hasTraceID() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'traceID' field */
    public com.handwin.serializable.module.TextMessagePacketAvro.Builder clearTraceID() {
      fieldSetFlags()[16] = false;
      return this;
    }

    @Override
    public TextMessagePacketAvro build() {
      try {
        TextMessagePacketAvro record = new TextMessagePacketAvro();
        record.cmsgID = fieldSetFlags()[0] ? this.cmsgID : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.content = fieldSetFlags()[1] ? this.content : (java.nio.ByteBuffer) defaultValue(fields()[1]);
        record.from = fieldSetFlags()[2] ? this.from : (java.nio.ByteBuffer) defaultValue(fields()[2]);
        record.messageId = fieldSetFlags()[3] ? this.messageId : (java.lang.Long) defaultValue(fields()[3]);
        record.messageServiceType = fieldSetFlags()[4] ? this.messageServiceType : (java.lang.Integer) defaultValue(fields()[4]);
        record.messageType = fieldSetFlags()[5] ? this.messageType : (java.lang.Integer) defaultValue(fields()[5]);
        record.messageFlag = fieldSetFlags()[6] ? this.messageFlag : (java.lang.Integer) defaultValue(fields()[6]);
        record.appID = fieldSetFlags()[7] ? this.appID : (java.lang.Integer) defaultValue(fields()[7]);
        record.vHead = fieldSetFlags()[8] ? this.vHead : (java.lang.Integer) defaultValue(fields()[8]);
        record.packetSize = fieldSetFlags()[9] ? this.packetSize : (java.lang.Integer) defaultValue(fields()[9]);
        record.secrect = fieldSetFlags()[10] ? this.secrect : (java.lang.Integer) defaultValue(fields()[10]);
        record.tempID = fieldSetFlags()[11] ? this.tempID : (java.lang.Integer) defaultValue(fields()[11]);
        record.timeStamp = fieldSetFlags()[12] ? this.timeStamp : (java.lang.Long) defaultValue(fields()[12]);
        record.version = fieldSetFlags()[13] ? this.version : (java.lang.Long) defaultValue(fields()[13]);
        record.zip = fieldSetFlags()[14] ? this.zip : (java.lang.Boolean) defaultValue(fields()[14]);
        record.toUser = fieldSetFlags()[15] ? this.toUser : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.traceID = fieldSetFlags()[16] ? this.traceID : (java.lang.Integer) defaultValue(fields()[16]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
